<?php if( !defined('MRGAUSS') ){ echo basename(__FILE__); exit; }
 /* CACHE CREATED: 1584083789.441 (2020-03-13 09:16:29) */
return array (
  3 => 
  array (
    'id' => '3',
    'ts' => '2020-01-02 15:40:23.725801',
    'region_id' => '1',
    'reagent_id' => '10',
    'quantity_inc' => '200',
    'inc_date' => '2020-01-01',
    'inc_expert_id' => '1',
    'group_id' => '1',
    'quantity_left' => '90',
    'clearence_id' => '2',
    'create_date' => '2019-01-01',
    'dead_date' => '2023-01-01',
    'is_sertificat' => '1',
    'creator' => 'Юрія-фарм',
    'reagent_state_id' => '2',
    'danger_class_id' => '2',
    'is_suitability' => '1',
    'comment' => 'хуйня',
    'safe_place' => 'тестове місце',
    'safe_needs' => 'тестові умови',
    'created_ts' => '2020-03-12 09:48:19.879959',
    'reagent_name' => 'Ацетон',
    'reagent_units' => 'Літри',
    'expert_name' => 'Роман',
    'expert_surname' => 'Пташкін',
    'expert_phname' => 'Леонідович',
    'quantity_dispersed' => '110',
    'quantity_not_used' => '109.3',
  ),
  7 => 
  array (
    'id' => '7',
    'ts' => '2020-03-12 17:40:18.36426',
    'region_id' => '1',
    'reagent_id' => '22',
    'quantity_inc' => '10',
    'inc_date' => '2020-01-01',
    'inc_expert_id' => '1',
    'group_id' => '1',
    'quantity_left' => '7',
    'clearence_id' => '2',
    'create_date' => '2019-07-10',
    'dead_date' => '2021-05-13',
    'is_sertificat' => '0',
    'creator' => 'Самжене',
    'reagent_state_id' => '1',
    'danger_class_id' => '1',
    'is_suitability' => '0',
    'comment' => '',
    'safe_place' => 'В пляшках',
    'safe_needs' => 'Шоб холодненька була',
    'created_ts' => '2020-03-12 17:40:18.36426',
    'reagent_name' => 'Етанол',
    'reagent_units' => 'Літри',
    'expert_name' => 'Роман',
    'expert_surname' => 'Пташкін',
    'expert_phname' => 'Леонідович',
    'quantity_dispersed' => '3',
    'quantity_not_used' => '3',
  ),
); 
/* COMMENT:  */

?>